name: Release
on:
  release: 
    types: [published]
  workflow_dispatch: 
jobs: 
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      - name: Setup Velopack
        run: |
          dotnet tool update -g vpk
      - name: Build
        run: |
          dotnet publish -c Release --no-self-contained -r win-x64 -o publish -p:PublishTrimmed=true
          vpk download github --repoUrl https://github.com/rgbcraft/NewRGBLauncher/
          vpk pack -u NewRGB -o releases -p publish -f net8-x64-desktop -v ${{github.ref_name}}
          vpk upload github --repoUrl "https://github.com/rgbcraft/NewRGBLauncher/" --merge --releaseName v${{github.ref_name}} --tag ${{github.ref_name}} --token ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Velopack
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
          dotnet tool update -g vpk
      - name: Build
        run: |
          chmod +x build-linux.sh
          bash build-linux.sh ${{github.ref_name}} ${{ secrets.GITHUB_TOKEN }}