name: Release
on:
  release: 
    types: [published]
  workflow_dispatch: 
jobs: 
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      - name: Setup Velopack
        run: |
          dotnet tool update -g vpk
      - name: Build
        run: |
          build-win.bat ${{github.ref_name}}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NewRGB-Win
          path: releases/*
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            releases/*
          token: ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Velopack
        run: |
          dotnet tool update -g vpk
      - name: Build
        run: |
          chmod +x build-linux.sh
          bash build-linux.sh ${{github.ref_name}}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NewRGB-Linux
          path: releases/*
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            releases/*
          token: ${{ secrets.GITHUB_TOKEN }}